name: Trello workflow

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - dev

jobs:
  attach-trello:
    runs-on: ubuntu-latest
    name: Find trello link and attach to card
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: over-secured-devops/trello-actions/attach_to_trello-card-action@main
        with:
          trello-key: ${{ secrets.TRELLO_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}